version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5252:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - MongoDb__ConnectionString=mongodb://admin:admin123@mongodb:27017/?authSource=admin
      - MongoDb__DatabaseName=meteomonitor
      - Mqtt__BrokerHost=mqtt-broker
      - Mqtt__BrokerPort=1883
      - Mqtt__ClientId=backend-service
      - Mqtt__Topics__0=sensors/#
      - Blockchain__Enabled=true
      - Blockchain__RpcUrl=http://anvil:8545
      - Blockchain__PrivateKey=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - Blockchain__ContractAddress=0x5FbDB2315678afecb367f032d93F642f64180aa3
      - Blockchain__RewardAmount=10
      - Blockchain__ChainId=31337
    depends_on:
      - mongodb
      - mqtt-broker
      - anvil
    networks:
      - meteo-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - meteo-network

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    hostname: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - meteo-network

  anvil:
    build:
      context: ./anvil
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    networks:
      - meteo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - meteo-network

networks:
  meteo-network:
    driver: bridge